# Core
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'yioneko/nvim-yati'
depends = ['nvim-treesitter/nvim-treesitter']

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# UI
[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_better_performance = 1
let g:gruvbox_material_palette = 'original'
let g:gruvbox_material_enable_bold = 1
let g:gruvbox_material_diagnostic_text_highlight = 1
let g:gruvbox_material_diagnostic_line_highlight = 1
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'nvim-lua/lsp-status.nvim'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'arkav/lualine-lsp-progress'
depends = ['nvim-lualine/lualine.nvim']

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/popup.nvim', 'nvim-lua/plenary.nvim']

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
depends = ['nvim-telescope/telescope.nvim']

[[plugins]]
repo = 'nvim-telescope/telescope-ui-select.nvim'
depends = ['nvim-telescope/telescope.nvim']

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
depends = 'kyazdani42/nvim-web-devicons'
hook_add = '''
source $HOME/.config/nvim/conf/nvim-tree.lua.vim
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'akinsho/nvim-bufferline.lua'
depends = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'Yggdroot/indentLine'

# LSP

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
depends = ['neovim/nvim-lspconfig']

# Completion

[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'

[[plugins]]
repo = 'L3MON4D3/LuaSnip'

[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'

[[plugins]]
repo = 'onsails/lspkind-nvim'
depends = ['hrsh7th/nvim-cmp']

[[plugins]]
repo = 'windwp/nvim-autopairs'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source $HOME/.config/nvim/conf/vim-gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'pwntester/octo.nvim'
depends = [
  'nvim-telescope/telescope.nvim',
  'nvim-lua/plenary.nvim',
  'kyazdani42/nvim-web-devicons'
]
# misc

[[plugins]]
repo = 'lewis6991/impatient.nvim'

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
depends = ['nvim-treesitter/nvim-treesitter', 'tpope/vim-commentary']

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'rrethy/vim-hexokinase'
build = 'make hexokinase'
hook_add = '''
" Disable colour names
let g:Hexokinase_optInPatterns = [
\     'full_hex',
\     'triple_hex',
\     'rgb',
\     'rgba',
\     'hsl',
\     'hsla'
\ ]
'''

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = '''
source $HOME/.config/nvim/conf/vim-silicon.vim
'''

[[plugins]]
repo = 'simrat39/rust-tools.nvim'

[[plugins]]
repo = 'akinsho/flutter-tools.nvim'
depends = ['nvim-lua/plenary.nvim']
