require('plugins')
require('nvim-bufferline')
require('nvim-cmp')
-- require('nvim-dap')
require('nvim-lsp')
require('nvim-lualine')
require('nvim-octo')
require('nvim-telescope')
require('nvim-autopairs').setup({ check_ts = true })
require('tree-sitter')
